### ISSUE TITLE
for cameron

### ISSUE THREAD

**Issue by Jimmi08** [Jimmi08/e107_snippets#6]
This code in template works:

![image](https://cloud.githubusercontent.com/assets/5429548/14616419/aa48f99e-05aa-11e6-8f8b-7def77e60b2a.png)

All fields are done the same way:
(added option class and placeholder)
 
![image](https://cloud.githubusercontent.com/assets/5429548/14616644/8f6dfeb6-05ab-11e6-9d1f-bd75cd9d70da.png)

Result:
![image](https://cloud.githubusercontent.com/assets/5429548/14616462/d55615ea-05aa-11e6-96ef-f1c707b2a61f.png)

After using parm on password field:
![image](https://cloud.githubusercontent.com/assets/5429548/14616500/f4b36da2-05aa-11e6-8fc0-8763b9c36475.png)

fields dissapeared:
![image](https://cloud.githubusercontent.com/assets/5429548/14616518/072d4926-05ab-11e6-981e-9126af162da7.png)

After changing name of shortcodes 
![image](https://cloud.githubusercontent.com/assets/5429548/14616547/25d80438-05ab-11e6-89bd-ba6ccf4f3623.png)

field is back:

![image](https://cloud.githubusercontent.com/assets/5429548/14616682/b2bac9b2-05ab-11e6-9453-9f98a8031eb5.png)

**Comment by CaMer0n** [comment]
It's a bug in the parser. I'll fix it.  Btw: placeholder=xx should normally display 'xx' in the element. 
placeholder=LAN_WHATEVER  would be more consistent than using '1'

**Comment by Jimmi08** [comment]
@CaMer0n Thanks. I tried, it wasn't translated. Just displayed string LAN_WHATEVER.

**Comment by CaMer0n** [comment]
Okay, so we need to add support for that to the form_handler.
